Integrate Slack App with Pinecone
Aggregate-Intellect/practical-llms pull request #12
Opened 2023-06-25 09:40 UTC by 20001LastOrder

The `bolt_app` uses the official slack_bolt library supported to build Slack app with Python. The tool integrates the slack app with the Pinecone database by default, but it can be switched to a local vector database as well by switching the retrieval of the app from `vectorstores.py`

**Features**:
1. Respond to mentions and reply in a thread
2. The thread history is considered when conversation continues in the same thread
3. The Pinecone index is preloaded with documentation for different LLM-related libraries (see `scripts/Pinecone.ipynb`)
4. Each response is correspond with a reference on which library documentation was refered.

2023-06-25 09:41 UTC, 20001LastOrder commented
@saminegash , @babasahebpinjar

2023-06-26 09:35 UTC, saminegash requested changes
there is also another conflict here btw

2023-06-26 10:22 UTC, 20001LastOrder commented on apps/slackbot/Dockerfile
> +CMD ["python", "bolt_app.py"]
This is the new app that utilize pine cone. I didn’t change the other app.py file.

2023-06-26 10:31 UTC, saminegash commented on apps/slackbot/Dockerfile
> +CMD ["python", "bolt_app.py"]
Can you resolve thw conflict then

2023-06-26 10:44 UTC, 20001LastOrder commented on apps/slackbot/Dockerfile
> +CMD ["python", "bolt_app.py"]
Done

2023-06-26 10:55 UTC, saminegash approved these changes

2023-06-26 10:55 UTC, merged