fixed Aggregate-Intellect#23 and Aggregate-Intellect#38
Aggregate-Intellect/practical-llms pull request #56
Opened 2023-08-01 12:17 UTC by YujingYang666777

2023-08-01 12:41 UTC, saminegash requested changes
Can you rebase this plase and push?

2023-08-01 16:50 UTC, YujingYang666777 commented
The conflict is solved and it should be able to merge. please let me know if here is anything I need to change

2023-08-03 20:26 UTC, 20001LastOrder requested changes
Looks good to me but is the user tool added by intention?

2023-08-03 20:26 UTC, 20001LastOrder commented on apps/slackbot/tools.py
> +    tools.append(UserInputTool())
Is the UserTool supposed to b added in this pr?

2023-08-03 22:00 UTC, closed without merging