Solve Aggregate-Intellect#38 none command and Aggregate-Intellect#23 error handeling
Aggregate-Intellect/practical-llms pull request #63
Opened 2023-08-03 21:53 UTC by YujingYang666777

@20001LastOrder @saminegash I created a new pull request from a new branch. The main branch consists of several unrelated commits. Thanks for the review process

2023-08-04 03:15 UTC, saminegash requested changes
once addressed we can merge this

2023-08-04 03:15 UTC, saminegash commented on apps/slackbot/task_agent.py
>              print("reply:", assistant_reply)
remove this print

2023-08-04 03:15 UTC, saminegash commented on apps/slackbot/task_agent.py
>              # return assistant_reply
remove comments that are not necessary

2023-08-04 12:21 UTC, YujingYang666777 commented on apps/slackbot/task_agent.py
>              # return assistant_reply
addressed

2023-08-04 19:30 UTC, 20001LastOrder approved these changes

2023-08-09 16:03 UTC, 20001LastOrder commented
@saminegash Can you take a look and approve this?

2023-08-10 13:43 UTC, YujingYang666777 commented
@saminegash I think the requested changes are addressed. Could you please take a look?

2023-08-10 15:24 UTC, 20001LastOrder submitted a review, later dismissed

2023-08-11 07:18 UTC, saminegash requested changes

2023-08-11 07:18 UTC, saminegash commented on apps/slackbot/task_agent.py
>              print("action:", action)
why are printing here? do we need this?

2023-08-11 07:18 UTC, saminegash commented on apps/slackbot/task_agent.py
>                  else:
this is required to see the logs on aws fyi!

2023-08-14 14:34 UTC, YujingYang666777 commented
@saminegash I solved the conflict and not it should be ready to merge. Thanks!

2023-08-16 14:16 UTC, saminegash approved these changes

2023-08-16 14:18 UTC, merged